FROM gcc:latest

RUN apt-get update && apt-get install -y iproute2 net-tools traceroute htop kmod iputils-ping && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN make all
ENTRYPOINT ["./run-tcp-client.sh"]
