FROM gcc:latest

RUN apt-get update && apt-get install -y iproute2 net-tools traceroute htop kmod nginx iputils-ping tshark tcpdump libssl-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
COPY server.key server.crt client.crt ./

RUN make all
ENTRYPOINT ["./docker-entrypoint-server.sh"]
