interface: lanecove0
port: 5040
private_key_file: /lanecove/peer-1.key
pre_shared_key: some-psk
verbose: false

peers:
  - public_key: 871314e4518a393a3fe1c466471f33f620968ed194e2443a46795ecc94ffb410
    endpoint: lanecove-relay.jecklgamis.com:5040
    allowed_ips:
      - 10.9.0.0/24
