name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libssl-dev libyaml-dev

      - name: Build deb
        run: make deb

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.deb

  build-rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libssl-dev libyaml-dev rpm

      - name: Build rpm
        run: make rpm

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/rpm/RPMS/**/*.rpm
